name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SOURCE_BRANCH: "master"
      TARGET_BRANCH: "gh-pages"
    steps:
      - name: Checkout ${{env.SOURCE_BRANCH}}
        uses: actions/checkout@v2
        with:
          ref: ${{env.SOURCE_BRANCH}}
          fetch-depth: '0'
          path: '${{env.SOURCE_BRANCH}}'

      - name: Checkout ${{env.TARGET_BRANCH}}
        uses: actions/checkout@v2
        with:
          ref: ${{env.TARGET_BRANCH}}
          fetch-depth: '0'
          path: '${{env.TARGET_BRANCH}}'

      - name: Setup Git
        run: |
          git config --global user.name "ShotaAk"
          git config --global user.email "macakasit@gmail.com"

      - name: Sync & Push to ${{env.TARGET_BRANCH}}
        run: |
          cd ${GITHUB_WORKSPACE}/${{env.SOURCE_BRANCH}}
          # 最新コミットのハッシュを取得し、${TARGET_BRANCH}のコミットメッセージに使う
          HASH=`git rev-parse --short HEAD`
          # rsyncでファイルをコピー
          # -a:とりあえず付けとけ -v:動作ログを見えるように --delete:sourceにないファイルを削除
          # --exclude:除外するファイル
          rsync -av --delete --exclude '.*' ${GITHUB_WORKSPACE}/${{env.SOURCE_BRANCH}}/ ${GITHUB_WORKSPACE}/${{env.TARGET_BRANCH}}
          cd ${GITHUB_WORKSPACE}/${{env.TARGET_BRANCH}}
          # exit if nothing to commit
          git status | grep -q "nothing" && exit 0
          # commit updated files
          git add .
          git commit -m "deploy: ${HASH}"
          git push -q origin ${{env.TARGET_BRANCH}}
